FROM confluentinc/cp-kafka-connect-base:5.1.1

ENV PLUGINS_DIR=/usr/share/confluent-hub-components/

USER root

RUN mkdir -p ${PLUGINS_DIR}/secret-provider \
        && wget -qP ${PLUGINS_DIR}/secret-provider https://github.com/lensesio/secret-provider/releases/download/2.1.6/secret-provider-2.1.6-all.jar

ENV CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components/
ENV CLASSPATH=${PLUGINS_DIR}/secret-provider/*
ENV CUB_CLASSPATH='"/etc/confluent/docker/docker-utils.jar:/usr/share/java/kafka/*:/usr/share/confluent-hub-components/secret-provider/*"'

ARG CONNECTORS="confluentinc/kafka-connect-jdbc:10.0.1"
RUN for c in ${CONNECTORS}; do confluent-hub install --no-prompt $c; done;












